packages:
  - include/common.yaml

substitutions:
  device: cellular

esphome:
  name: ${device}
  platform: ESP32
  board: wemos_d1_mini32

uart:
  baud_rate: 9600
  tx_pin: GPIO17
  rx_pin: GPIO18

logger:
  #baud_rate: 0 # disable uart logger on esp 8266    



api:
  services:
    - service: send_sms
      variables:
        recipient: string
        message: string
      then:
        - sim800l.send_sms:
            recipient: !lambda 'return recipient;'
            message: !lambda 'return message;'

    - service: dial
      variables:
        recipient: string
      then:
        - sim800l.dial:
            recipient: !lambda 'return recipient;'

text_sensor:
  - platform: template
    id: sms_sender
    name: "Sms Sender"

  - platform: template
    id: sms_message
    name: "Sms Message"

sim800l:
  on_sms_received:
    - logger.log:
        format: "Received '%s' from %s"
        args: [ 'message.c_str()', 'sender.c_str()' ]

#    - lambda: |-
#        if ( (id(sms_sender).state == "+79991234567") && ( (id(sms_message).state == "relay_1_on") OR (id(sms_message).state == "Relay_1_on") ) ) {
#              id(relay_1).turn_on();
#              }    
    - lambda: |-
        id(sms_sender).publish_state(sender);
        id(sms_message).publish_state(message);
