substitutions:
  PROJECT_NAME: amir.paulee
  CONFIG_FILE: cellular.yaml
  PROJECT_VERSION: "1.0"
  device: cellular

packages:
  board: !include include/tkv_board.yaml
  customer: !include include/paulee.yaml

uart:
  - baud_rate: 115200
    id: sim_uart
    tx_pin: GPIO17
    rx_pin: GPIO16
    debug:
      direction: BOTH
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_string(direction, bytes);

sim800l:
  uart_id: sim_uart
  on_sms_received:
    - logger.log:
        format: "Received '%s' from %s"
        args: [ 'message.c_str()', 'sender.c_str()' ]
    - lambda: |-
        id(sms_sender).publish_state(sender);
        id(sms_message).publish_state(message);
  on_incoming_call:
    - logger.log:
        format: "Incoming call from '%s'"
        args: ["caller_id.c_str()"]

sensor:
  - platform: sim800l
    rssi:
      name: "Sim800L RSSI"

binary_sensor:
  - platform: sim800l
    registered:
      name: "Sim800L Registered"

api:
  services:
    - service: send_sms
      variables:
        recipient: string
        message: string
      then:
        - sim800l.send_sms:
            recipient: !lambda 'return recipient;'
            message: !lambda 'return message;'

    - service: dial
      variables:
        recipient: string
      then:
        - sim800l.dial:
            recipient: !lambda 'return recipient;'

text_sensor:
  - platform: template
    id: sms_sender
    name: "Sms Sender"

  - platform: template
    id: sms_message
    name: "Sms Message"

logger:
  level: VERBOSE
  logs:
    json: DEBUG
    mdns: DEBUG
    improv_serial: DEBUG
  #  sim800l: VERBOSE