packages:
  - include/common.yaml

substitutions:
  device: display

esphome:
  name: ${device}
  platform: ESP32
  board: wemos_d1_mini32
#  includes:
#    - serial_over_wifi/stream_server.h
#    - serial_over_wifi/stream_server.cpp

<<: !include include/common.yaml

logger:
  #baud_rate: 0
  level: DEBUG

uart:
  #rx_pin: RX
  #tx_pin: TX
  rx_pin: GPIO34
  tx_pin: GPIO33
  baud_rate: 115200
  id: uart1

display:
  - platform: nextion
    uart_id: uart1
    id: display_nextion
    lambda: |-
      it.set_wait_for_ack(false);
      id(display_nextion).set_component_background_color("parents_up", id(dummy_switch).state ? "GREEN" : "GRAY");

binary_sensor:
  - platform: homeassistant
    id: dummy_switch
    entity_id: input_boolean.dummy
    internal: true
    on_state:
      then:
        - logger.log: "Switch Change"
        - lambda: |-
            id(display_nextion).set_component_background_color("parents_up", id(dummy_switch).state ? "GREEN" : "GRAY");


  - platform: nextion
    page_id: 0
    component_id: 4
    name: "parents_up"
    internal: true
    on_press:
      then:
        - logger.log: "Switch On"
        - homeassistant.service:
            service: homeassistant.toggle
            data:
              entity_id: input_boolean.dummy
    on_release:
      then:
        - logger.log: "Switch Off"

#custom_component:
#  - lambda: |-
#      auto stream_server = new StreamServerComponent(id(uart1));
#      return {stream_server};  

status_led:
  pin:
    number: LED
