packages:
  - include/common.yaml

substitutions:
  device: display

esphome:
  name: ${device}
  platform: ESP32
  board: wemos_d1_mini32
#  includes:
#    - serial_over_wifi/stream_server.h
#    - serial_over_wifi/stream_server.cpp

<<: !include include/common.yaml

logger:
  #baud_rate: 0
  level: DEBUG

#   on_message:
#     level: ERROR
#     then:
#       - globals.set:
#         id: log_line
#         value: '1'
# #      - lambda: |-
# #        strcpy(id(next), message);
# 
# #        id(display).set_component_text("textview", "Triggered on_message with level ");
# 
globals:
  - id: nextion_page_id
    type: int
    restore_value: no
    initial_value: '0'

  - id: log_line
    type: char [20]
    restore_value: false

#//id(display).set_component_text("textview", "Triggered on_message with level " + std::to_string(level) + ", tag " + tag + " and message " + message);  

uart:
  #rx_pin: RX
  #tx_pin: TX
  rx_pin: GPIO34
  tx_pin: GPIO33
  baud_rate: 115200
  id: uart1

display:
  - platform: nextion
    uart_id: uart1
    id: display_nextion
    lambda: |-
      it.set_wait_for_ack(false);
      //it.set_component_value("x0", 11);
      
      //it.set_component_value("x2", id(temp_1).state * 10);
      //it.set_component_value("x3", id(hum_1).state * 10);
      //it.set_component_value("x9", id(temp_2).state * 10);

      if (id(nextion_page_id) == 0) {
        it.set_component_text("t0", "Irrigation");  
      }
      /*      it.set_component_background_color("t40", 17013);
      it.set_component_text("textview", id(log_line));*/

sensor:
  - platform: homeassistant
    name: "Temp 1"
    id: temp_1
    entity_id: sensor.inside_temperature

  - platform: homeassistant
    name: "Humidity 1"
    id: hum_1
    entity_id: sensor.inside_humidity

  - platform: homeassistant
    name: "Temp 2"
    id: temp_2
    entity_id: sensor.outside_temperature

switch:
  - platform: nextion
    page_id: 0
    component_id: 1
    button_id: "bt1"
    name: "Kitchen up"
  - platform: nextion
    page_id: 0
    component_id: 2
    button_id: "bt0"
    name: "Kitchen down"

  - platform: nextion
    page_id: 0
    component_id: 3
    button_id: "bt2"
    name: "Yard up"
#  - platform: nextion
#    page_id: 0
#    component_id: 4
#    button_id: "bt3"
#    name: "Yard down"

  - platform: nextion
    page_id: 0
    component_id: 16
    button_id: "bt8"
    name: "Win1 up"
  - platform: nextion
    page_id: 0
    component_id: 17
    button_id: "bt9"
    name: "Win1 down"

  - platform: nextion
    page_id: 0
    component_id: 18
    button_id: "bt10"
    name: "Win2 up"
  - platform: nextion
    page_id: 0
    component_id: 19
    button_id: "bt11"
    name: "Win2 down"

  - platform: nextion
    page_id: 0
    component_id: 7
    button_id: "bt6"
    name: "Floor1 up"
  - platform: nextion
    page_id: 0
    component_id: 24
    button_id: "bt14"
    name: "Floor1 down"


  - platform: nextion
    page_id: 0
    component_id: 5
    button_id: "bt4"
    name: "Win3 up"
  - platform: nextion
    page_id: 0
    component_id: 6
    button_id: "bt5"
    name: "Win3 down"

  - platform: nextion
    page_id: 0
    component_id: 22
    button_id: "bt12"
    name: "Win4 up"
  - platform: nextion
    page_id: 0
    component_id: 23
    button_id: "bt13"
    name: "Win4 down"

  - platform: nextion
    page_id: 0
    component_id: 8
    button_id: "bt7"
    name: "Floor2 up"
  - platform: nextion
    page_id: 0
    component_id: 27
    button_id: "bt15"
    name: "Floor2 down"

binary_sensor:
  - platform: nextion
    page_id: 0
    component_id: 11
    name: "page1"
    internal: true
    on_release:
      then:
        - lambda: |-
            id(display_nextion).set_component_text("t0", "Switching");  
            id(nextion_page_id)=1;
            id(display_nextion).goto_page("1");
        - component.update: display_nextion

  - platform: nextion
    page_id: 1
    component_id: 5
    name: "page0"
    internal: true
    on_release:
      then:
        - lambda: |-
            id(nextion_page_id)=0;
            id(display_nextion).goto_page("0");
        - component.update: display_nextion





  - platform: homeassistant
    id: dummy_switch
    entity_id: input_boolean.dummy
    on_state:
      then:
        - logger.log: "Switch Change"
        - lambda: 'id(display_nextion).send_command_printf("Button.parents_up.val=%d",id(dummy_switch).state);'



  - platform: nextion
    page_id: 0
    component_id: 4
    name: "mixer"
    internal: true
    on_press:
      then:
        - logger.log: "Switch On"
        - homeassistant.service:
            service: homeassistant.toggle
            data:
              entity_id: input_boolean.dummy
    on_release:
      then:
        - logger.log: "Switch Off"

  - platform: nextion
    page_id: 0
    component_id: 5
    name: "mixer"

  - platform: nextion
    page_id: 0
    component_id: 59
    name: "dryer"

  - platform: nextion
    page_id: 0
    component_id: 60
    name: "heater_pump"

#custom_component:
#  - lambda: |-
#      auto stream_server = new StreamServerComponent(id(uart1));
#      return {stream_server};  

status_led:
  pin:
    number: LED
