substitutions:
  PROJECT_NAME: amir.gy
  CONFIG_FILE: gy-oz0-0-10-1.yaml
  PROJECT_VERSION: "1.0"
  device: ozone1
    
packages:
  board: !include include/tkv_board.yaml
  gy: !include include/gy.yaml
  ozone_3: !include { file: modbus/ozone.yaml, vars: { addr: 3 } } 

uart:
  id: modbus_uart
  rx_pin: GPIO17
  tx_pin: GPIO16
  baud_rate: 9600
  stop_bits: 1

modbus:
  id: modbus_comp
  uart_id: modbus_uart
  send_wait_time: 200ms
