packages:
  - include/common.yaml

esphome:
  name: ${device}

esp8266:
  board: esp8285

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "${device} Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${device} Relay"
    pin: GPIO12
    id: relay
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

output:
  - platform: gpio
    pin:
      number: GPIO13
      inverted: yes
    id: led