packages:
  - include/common.yaml

substitutions:
  device: level1
  interval_level: 5s

esphome:
  name: ${device}
  platform: ESP32
  board: esp32dev

status_led:
  pin:
    number: GPIO23

sensor:
  - platform: template
    name: "${device} Level 1 Raw"
    accuracy_decimals: 3
    unit_of_measurement: "V"
    id: level1_raw

  - platform: adc
    pin: GPIO35
    name: "${device} Level 1"
    attenuation: 11db
    update_interval: ${interval_level}
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
        - 0.8 -> 0
        - 2.5 -> 800
      - throttle: 1s
    unit_of_measurement: "L"
    on_raw_value:
      then:
        lambda: id(level1_raw).publish_state(x);

  - platform: template
    name: "${device} Level 2 Raw"
    accuracy_decimals: 3
    unit_of_measurement: "V"
    id: level2_raw

  - platform: adc
    pin: GPIO34
    name: "${device} Level 2"
    attenuation: 11db
    update_interval: ${interval_level}
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
        - 0.8 -> 0
        - 2.5 -> 800
      - throttle: 1s
    unit_of_measurement: "L"
    on_raw_value:
      then:
        lambda: id(level2_raw).publish_state(x);

