substitutions:
  PROJECT_NAME: amir.paulee
  CONFIG_FILE: level1.yaml
  PROJECT_VERSION: "1.0"
  device: level1
  interval_level: 5s
    
packages:
  common: !include include/common.yaml
  esp: !include include/esp32.yaml
  board: !include include/tkv_board.yaml
  paulee: !include include/paulee.yaml

sensor:
  - platform: template
    name: "${device} Level 1 Raw"
    accuracy_decimals: 3
    unit_of_measurement: "V"
    id: level1_raw

  - platform: adc
    pin: GPIO35
    name: "${device} Level 1"
    attenuation: 11db
    update_interval: ${interval_level}
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
        - 0.8 -> 0
        - 2.5 -> 800
      - throttle: 1s
    unit_of_measurement: "L"
    on_raw_value:
      then:
        lambda: id(level1_raw).publish_state(x);

  - platform: template
    name: "${device} Level 2 Raw"
    accuracy_decimals: 3
    unit_of_measurement: "V"
    id: level2_raw

  - platform: adc
    pin: GPIO34
    name: "${device} Level 2"
    attenuation: 11db
    update_interval: ${interval_level}
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
        - 0.8 -> 0
        - 2.5 -> 800
      - throttle: 1s
    unit_of_measurement: "L"
    on_raw_value:
      then:
        lambda: id(level2_raw).publish_state(x);

