packages:
  - include/common.yaml

substitutions:
  device: modbus

esphome:
  name: ${device}
  platform: ESP32
  board: wemos_d1_mini32

<<: !include include/common.yaml

logger:
  level: DEBUG
  baud_rate: 0

web_server:
  port: 80

status_led:
  pin: LED

uart:
  id: mod_bus
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600
  stop_bits: 1

modbus_controller:
  uart_id: mod_bus
  command_throttle: 0ms
  id: traceranx
  address: 0x2a

  sensors:
    - id: humidity
      name: "humidity"
      address: 0
      unit_of_measurement: "%"
      modbus_functioncode: "read_holding_registers"
      value_type: U_WORD
      accuracy_decimals: 1
      filters:
      - multiply: 0.1


    - id: temperature
      name: "temperature"
      address: 1
      unit_of_measurement: "C"
      modbus_functioncode: "read_holding_registers"
      value_type: U_WORD
      accuracy_decimals: 1
      filters:
      - multiply: 0.1

  update_interval: 5s

