packages:
  - include/common.yaml

substitutions:
  device: s39
  slave: "39"
  grace_period: "2s"
    
sensor:
  - platform: modbus_controller
    id: temperature
    name: "${device} temperature"
    address: 4
    offset: 0
    unit_of_measurement: "°C"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

