substitutions:
  PROJECT_NAME: amir.gy
  CONFIG_FILE: modbus_ozone1.yaml
  PROJECT_VERSION: "1.0"
  device: ozone1
  slave: "03"
    
packages:
  common: !include include/common.yaml
  modbus: !include include/modbus_common.yaml
  board: !include include/esp32.yaml
  
sensor:
  - platform: modbus_controller
    name: "${device} gas"
    address: 0
    register_type: read
    value_type: FP32_R
    accuracy_decimals: 2

    lambda: |-
      ESP_LOGI("","Lambda incoming value=%f - data array size is %d",x,data.size());
      ESP_LOGI("","Sensor properties: adress = 0x%X, offset = 0x%X value type=%d", item->start_address, item->offset, (int)item->sensor_value_type);
      int i=0 ;
      for (auto val : data) {
        ESP_LOGI("","data[%d]=0x%02X (%d)", i, data[i], data[i]);
        i++;
      }
      return x ;    

  - platform: modbus_controller
    name: "${device} temperature"
    unit_of_measurement: "°C"
    address: 1
    register_type: read
    value_type: FP32_R
    accuracy_decimals: 2

  - platform: modbus_controller
    name: "${device} humidity"
    unit_of_measurement: "%"
    address: 2
    register_type: read
    value_type: FP32_R
    accuracy_decimals: 2
