substitutions:
  PROJECT_NAME: amir.paulee
  CONFIG_FILE: modbus_s39.yaml
  PROJECT_VERSION: "1.0"
  device: s39
  slave: "39"
  grace_period: "2s"
    
packages:
  modbus: !include include/modbus_common.yaml
  #- include/common.yaml

sensor:
  - platform: modbus_controller
    id: temperature
    name: "${device} temperature"
    address: 4
    offset: 0
    unit_of_measurement: "°C"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

