packages:
  - include/common.yaml

substitutions:
  device: pt100x2

esphome:
  name: ${device}
  platform: ESP32
  board: wemos_d1_mini32

status_led:
  pin:
    number: LED
    inverted: yes

spi:
  # See pingout of esp12e at https://components101.com/wireless/esp12e-pinout-datasheet
    mosi_pin: GPIO13
    miso_pin: GPIO12
    clk_pin: GPIO14

sensor:
  - platform: max31865
    name: ${device} Temperature1
    cs_pin: GPIO15
    reference_resistance: 430 立
    rtd_nominal_resistance: 100 立
    update_interval: 30s

  - platform: max31865
    name: ${device} Temperature2
    cs_pin: GPIO16
    reference_resistance: 430 立
    rtd_nominal_resistance: 100 立
    update_interval: 30s
      #mains_filter: 50HZ
      #rtd_wires: 3
