packages:
  - include/common.yaml

substitutions:
  device: serial

esphome:
  name: ${device}
  platform: ESP32
  board: wemos_d1_mini32

<<: !include include/common.yaml

logger:
  baud_rate: 0
  #baud_rate: 115200

uart:
- id: uart0
  rx_pin: GPIO34
  tx_pin: GPIO33
  baud_rate: 115200
  stop_bits: 1

#- id: uart1
#  rx_pin: 9
#  tx_pin: 10
#  baud_rate: 9600
#  stop_bits: 1

external_components:
  - source: github://oxan/esphome-stream-server

stream_server:  
   uart_id: uart0
   port: 1234  

binary_sensor:
  - platform: status
    name: ${device} Status

status_led:
  pin:
    number: LED

