substitutions:
  PROJECT_NAME: amir.paulee
  CONFIG_FILE: sv-2.yaml
  PROJECT_VERSION: "1.0"
  device: sv_2
  hostname: sv-2

packages:
  common: !include include/common.yaml
  th16: !include include/sonoff_sv.yaml
  paulee: !include include/paulee.yaml

esphome:
  name: ${hostname}