packages:
  - include/common.yaml

substitutions:
  device: uploader

esphome:
  name: ${device}
  platform: ESP32
  board: wemos_d1_mini32

logger:
  #baud_rate: 0
  level: DEBUG

status_led:
  pin:
    number: LED
