modbus_controller:
  - id: temp_${addr}
    modbus_id: modbus_comp
    command_throttle: 100ms
    address: ${addr}
    update_interval: 10s
    setup_priority: -10  
  
sensor:
  - platform: modbus_controller
    name: "${device} temperature ${addr}"
    modbus_controller_id: temp_${addr}
    address: 4
    offset: 0
    unit_of_measurement: "°C"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
    - multiply: 0.1

