#!/usr/bin/python

import os
import sys
import subprocess

version_file = sys.argv[1]
filename = os.path.basename(sys.argv[2])

version = subprocess.check_output("echo `hostname` `git describe --all --long  --dirty` `date --rfc-email`", shell=True, text=True).strip()

autosensors = """# This file is autogenerated. Do not edit

text_sensor:
  - platform: template
    name: ${device} Version
    lambda: !lambda return {"%s"};

  - platform: template
    name: ${device} Filename
    lambda: !lambda return {"%s"};
""" % (version, filename)

with open(version_file, "w") as f:
    f.write(autosensors)