esphome:
  build_path: "obj/${device}"
  project:
    name: ${PROJECT_NAME}
    version: ${PROJECT_VERSION}

logger:
  level: DEBUG

wifi:
  networks:
  - ssid: !secret ephy_ssid
    password: !secret ephy_password
    priority: 5

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device} Hotspot
    password: !secret ap_password

captive_portal:

api:

ota:

web_server:
  port: 80

switch:
  - platform: restart
    name: ${device} Restart

button:
  - platform: safe_mode
    name: "${device} Safe Mode"

sensor:
  - platform: wifi_signal
    name: ${device} Wifi Signal
    update_interval: 60s
  - platform: uptime
    name: ${device} Uptime
  
text_sensor:
  - platform: version
    name: ${device} ESPHomelib Version
    id: version_esphomelib
  - platform: wifi_info
    ip_address:
      name: ${device} IP Address
    ssid:
      name: ${device} Connected SSID
    bssid:
      name: ${device} Connected BSSID

  - platform: template
    name: ${device} Version
    lambda: !lambda return {"${PROJECT_VERSION}"};

  - platform: template
    name: ${device} Filename
    lambda: !lambda return {"${CONFIG_FILE}"};

dashboard_import:
  package_import_url: github://amirv/esphome-config/${CONFIG_FILE}

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:
