# This file is for pow R2 in older pow, there used to be a different power sensor

<<: !include sonoff_common.yaml

# Enable logging
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

binary_sensor:
  - platform: status
    name: ${device} Status
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ${device} Button
    on_press:
      - switch.toggle: ${device}_relay

switch:
  - platform: gpio
    name: ${device} Relay
    pin: GPIO12
    id: ${device}_relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

sensor:
  - platform: cse7766
    current:
      name: ${device} Current
    voltage:
      name: ${device} Voltage
    power:
      name: ${device} Power
    update_interval: 5s
